# Generated by Django 5.2.8 on 2025-12-27 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloapp', '0002_genre_movie_profile_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='genres',
            field=models.ManyToManyField(blank=True, to='helloapp.genre'),
        ),
    ]
