# Generated by Django 6.0.1 on 2026-01-09 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helloapp', '0003_profile_friends'),
        ('helloapp', '0005_loginattempt'),
    ]

    operations = [
    ]
